# Use the README file as a reference to customize settings.

Capital:
  fields:
    default: key, value, created_at, updated_at
    form: key, value
  relationships:
  application: Application
  #order_by: key