# Use the README file as a reference to customize settings.

Credit:
  fields:
    default: currency, amount, rate, status, period, user_id, position_id, created_at, updated_at
    form: currency, amount, rate, status, period, user_id, position_id
  relationships: 
  application: Application
  order_by: -id
  #filters: status
