# Use the README file as a reference to customize settings.

Stat:
  fields:
    default: key, value, created_at, updated_at
    form: key, value
  relationships: 
  application: Application
  order_by: -id
